### ISSUE TITLE
Asset balances of ethereum network are not being updated

### ISSUE THREAD

**Issue by Nhixson17** [leverim/sovryn-mobile#124]
Sent my SOV balance from Sovryn browser to my mobile wallet and have not received either transaction. Am I missing something???

**Comment by grinry** [comment]
@Nhixson17 mobile wallet only shows outgoing transactions, it does not track incoming transactions. Balance still should be updated if transaction was confirmed.
You can confirm if transaction is confirmed in the rsk explorer - https://explorer.rsk.co by entering your mobile app wallet address.
If it's confirmed, but balance does not show up in the app - make sure you have enabled correct network in the app settings (settings -> networks).
You can also try manually refreshing data by app screen down until you see spinning progress bar and then releasing it.

**Comment by Nhixson17** [comment]
I confirmed the transaction. Tried refreshing, and network settings are correct…I sent three all three were confirmed and only one showed up in my wallet… 

transaction ID  0x0fc69ae07363d5de29ba0a1aa6eceea9263465d6687076e58cab1f31ce9f29c0

**Comment by Nhixson17** [comment]
My transaction on metamask says approve sov spend limit. I followed promps on Sovryn to send… why would it say spend?

**Comment by grinry** [comment]
@Nhixson17, I see you were using bridge and bridged SOV to eSOV on ethereum network. Was it your intention to send it to ethereum network?

Your tokens currently are on ETH network on this wallet: https://etherscan.io/address/0xeea534FF31E62CBe79CD83f3Ee53E977216EE021#tokentxns

If it's a wallet of mobile app, then you need to enable ethereum network in the settings too

**Comment by Nhixson17** [comment]
The first transaction I tried sending from Sovryn web browser to my mobile app I sent to SOv network. Then once I didn’t receive my funds I realized I may have had to send to esov wallet since that was only option the browser gave me… so I sent another one to esov wallet address on my Sovryn mobile app and didn’t receive that one either…. The browser only allowed it to be sent to etherium network or eSOV with my metamask wallet. My etherium network is enabled and it’s still not showing up… On Nov 24, 2022, at 11:17 AM, Rytis Grincevičius ***@***.***> wrote:﻿
@Nhixson17, I see you were using bridge and bridged SOV to eSOV on ethereum network. Was it your intention to send it to ethereum network?
Your tokens currently are on ETH network on this wallet: https://etherscan.io/address/0xeea534FF31E62CBe79CD83f3Ee53E977216EE021#tokentxns
If it's a wallet of mobile app, then you need to enable ethereum network in the settings too

**Comment by grinry** [comment]
> My transaction on metamask says approve sov spend limit. I followed promps on Sovryn to send… why would it say spend?

Ah, yeah, I see now that bridging wasn't your intention. https://live.sovryn.app has "send" functionality that's is actually a bridging to another network and not just sending to another rsk wallet. To just send to the another wallet you could have just used your wallet (metamask for example).

 In the end, your funds are not lost, just in the wrong network. You should see them as ESOV on ethereum network

**Comment by Nhixson17** [comment]
Thanks so much for help. Trying to figure this out…. That makes sense However… I’ve added ESOV to my metamask and funds are there still and also have etherium network enabled on my Sovryn mobile app wallet and funds are not there either…On Nov 24, 2022, at 11:23 AM, Rytis Grincevičius ***@***.***> wrote:﻿

My transaction on metamask says approve sov spend limit. I followed promps on Sovryn to send… why would it say spend?

Ah, yeah, I see now that bridging wasn't your intention. https://live.sovryn.app has "send" functionality that's is actually a bridging to another network and not just sending to another rsk wallet. To just send to the another wallet you could have just used your wallet (metamask for example).
In the end, your funds are not lost, just in the wrong network. You should see them as ESOV on ethereum network

**Comment by grinry** [comment]
@Nhixson17, I checked on my mobile wallet and looks like it's indeed not updating any ethereum network balances. I'm marking this issue as a bug, but it will take time to prepare a fix and publish a new app to the app stores.

In meantime, to use your eSOV, you can import the private key of your sovryn-mobile app (export is in settings -> wallet -> {your wallet} -> view private key) to the metamask.

**Comment by grinry** [comment]
fix was applied, now we can only wait for app store to approve and publish new app version
